

<FL>:
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size

    Image:
        pos_hint: {"top":1,"right":1}
        source: "images/settings.png"
        align: 'left'
        size_hint: 0.1,0.1
    Image:
        pos_hint: {"top":1.1 , "x":0.2}
        source: "images/icon.png"
        keep_ratio: True
        size_hint: 0.65,0.65

    Label:
        color: 0,0,0,1
        text:"Start:"
        font_size: 50
        pos_hint: {"top":1.05}

    Image:
        pos_hint: {"top":0.48, "x":0.4}
        source: "images/play.jpg"
        keep_ratio: True
        size_hint: 0.2,0.2

    Label:
        color: 0,0,1,1
        text:"Blocked ads:" + str(root.proxy_server.get_blocked_ads())
        font_size: 30
        pos_hint: {"y":-0.35}



