<FL>
    btn:btn
    count:count
    canvas.before:
        Color:
            rgba: 0, 0, 0, 0
        Rectangle:
            pos: self.pos
            size: self.size

    Image:
        pos_hint: {"top":1,"right":1}
        source: "images/settings.png"
        align: 'left'
        size_hint: 0.1,0.1
    Image:
        pos_hint: {"top":1.1 , "x":0.2}
        source: "images/icon.png"
        keep_ratio: True
        size_hint: 0.65,0.65

    Label:
        color: 0,0,0,1
        text:"Start:"
        font_size: 50
        pos_hint: {"top":1.05}

    Image:
        id:btn
        pos_hint: {"top":0.48, "x":0.4}
        source: "images/play.png"
        keep_ratio: True
        size_hint: 0.2,0.2

    Label:
        id: count
        color: 0,0,1,1
        text:"Blocked ads:" + str(root.proxy_server.get_blocked_ads())
        font_size: 30
        pos_hint: {"y":-0.35}

<SettingsGrid>
    ads: ads
    malwares: malwares
    eighteen: eighteen
    FloatLayout:
        size: root.width, root.height

        Image:
            pos_hint: {"top":0.65,"left":0.5}
            source: "images/custome.png"
            align: 'left'
            size_hint: 1,1

        Image:
            pos_hint: {"top":1,"left":1}
            source: "images/back.png"
            align: 'left'
            size_hint: 0.1,0.1

        GridLayout:
            cols:2
            rows:6
            size_hint: 1,0.7
            pos_hint: {"top":0.9}
            Label:
                text: "Ad filtering: "
                font_size: 20

            Switch:
                id: ads
            Label:
                text: "Malware blocking: "
                font_size: 20

            Switch:
                id: malwares
            Label:
                text: "18+ filtering: "
                font_size: 20

            Switch:
                id: eighteen


<MainScreen>
    FL:

<SettingsScreen>
    SettingsGrid:

<CustomeScreen>
    Custome:
        customebox: customebox
        size: root.width, root.height

        Image:
            pos_hint: {"top":1,"left":1}
            source: "images/back.png"
            align: 'left'
            size_hint: 0.1,0.1
        Label:
            pos_hint: {"top":1.3}
            font_size: 25
            text: "Please enter your custome blocks in the text box below \nevery domain in a new line\nEx: www.facebook.com"
        TextInput:
            id: customebox
            size_hint: 1,0.7